### ISSUE TITLE
Documentation + large deformation stress

### ISSUE THREAD

**Issue by Sina-av** [hugary1995/raccoon#104]
Hey @hugary1995!
I was once again going over the code and found some points and questions that I'd like to share with you:

1. (Not really important!) Here the name of the second parameter in the documentation should change from "exponentiate" to "**plasticity_update**"
https://github.com/hugary1995/raccoon/blob/eb31a918882df0b0b2fa03af5a9bacde1fa33529/include/materials/large_deformation_models/LargeDeformationElasticityModel.h#L37-L43
2. (Typo) Here the name of the material should be CNH (instead of Hencky)
https://github.com/hugary1995/raccoon/blob/eb31a918882df0b0b2fa03af5a9bacde1fa33529/tutorials/homogeneous_cube/CNH_J2_powerlawhardening/elastoplasticity_fracture.i#L143-L145
3. I also have a question on large deformation elasticity models. For an elastic simulation, in **ComputeLargeDeformationStress**, we call the **updateState** method of the underlying elasticity model in which **computeCauchyStress** is used with the help of the Mandel stress coming form **computeMandelStress**. However, in CNH model under (e.g.) **computeMandelStressNoDecomposition** method, the calculated stress is the Kirchhoff stress. Would this cause any problem in the calculations? (As that Kirchhoff stress  is treated as the Mandel stress). Please let me know if I'm missing something.
Thanks a lot!

**Comment by hugary1995** [comment]
Thanks for pointing out the typos, I'll fix them.

Regarding the Kirchhoff stress, this is a very good question. There are some historical reasons for this discrepancy. The relation between the Kirchhoff stress (\tau) and the Mandel stress (M) is given by
```
\tau = F^e^{-T} M F^e^T
```
where `F^e` is the elastic deformation gradient. In most of the existing FEM packages for finite deformation (crystal)plasticity, it is assumed that `F^e` is close to identity when plasticity occurs, which leads to the approximation `\tau ~= M`. This assumption is particularly good for many metals. I kept this approximation so that I can benchmark my results with those obtained from other packages.

I'll add the above explanation as comment in the code.

As I'm drafting this answer, I realize that adding an extra operation to convert the Kirchhoff stress to the Mandel stress in `computeMandelStressNoDecomposition` and `computeMandelStressVolDevDecomposition` is probably not a bad idea. I'll do some testing and see how much of an additional cost as a result of that. If it is cheap, then why not? :)

**Comment by Sina-av** [comment]
Thank you so much @hugary1995 for the explanation. It is really helpful. 
I also think that adding the extra operation to convert the stress might be a good idea (of course after considering its cost). (Also this conversion might be helpful for cases that one might just use CNH model in an elastic simulation where there is no plasticity at all).
Thanks again.

**Comment by hugary1995** [comment]
It turns out I don't need to change anything to convert the Kirchhoff stress to the Mandel stress -- for isotropic materials, they coincide.

**Comment by Sina-av** [comment]
Hi @hugary1995! I was going over this issue again. Looking at your last comment. I was wondering if you have a reference that I can look into regarding "Kirchhoff stress and the Mandel stress -- for isotropic materials, they coincide". I'm still not sure how this can happen (for the most general case)
Thanks a lot!
